/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.online.shop.system.kafka.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum paymentOrderStatus implements org.apache.avro.generic.GenericEnumSymbol<paymentOrderStatus> {
  PAID, CANCELLED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"paymentOrderStatus\",\"namespace\":\"com.online.shop.system.kafka.avro.model\",\"symbols\":[\"PAID\",\"CANCELLED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
