/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.online.shop.system.kafka.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ProductRatingAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3081401625170831425L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProductRatingAvroModel\",\"namespace\":\"com.online.shop.system.kafka.avro.model\",\"fields\":[{\"name\":\"productID\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"rating\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
  }

  private static final BinaryMessageEncoder<ProductRatingAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProductRatingAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProductRatingAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProductRatingAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProductRatingAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProductRatingAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProductRatingAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProductRatingAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProductRatingAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.UUID productID;
  private int rating;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProductRatingAvroModel() {}

  /**
   * All-args constructor.
   * @param productID The new value for productID
   * @param rating The new value for rating
   */
  public ProductRatingAvroModel(java.util.UUID productID, java.lang.Integer rating) {
    this.productID = productID;
    this.rating = rating;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return productID;
    case 1: return rating;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.Conversions.UUIDConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: productID = (java.util.UUID)value$; break;
    case 1: rating = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'productID' field.
   * @return The value of the 'productID' field.
   */
  public java.util.UUID getProductID() {
    return productID;
  }


  /**
   * Sets the value of the 'productID' field.
   * @param value the value to set.
   */
  public void setProductID(java.util.UUID value) {
    this.productID = value;
  }

  /**
   * Gets the value of the 'rating' field.
   * @return The value of the 'rating' field.
   */
  public int getRating() {
    return rating;
  }


  /**
   * Sets the value of the 'rating' field.
   * @param value the value to set.
   */
  public void setRating(int value) {
    this.rating = value;
  }

  /**
   * Creates a new ProductRatingAvroModel RecordBuilder.
   * @return A new ProductRatingAvroModel RecordBuilder
   */
  public static com.online.shop.system.kafka.avro.model.ProductRatingAvroModel.Builder newBuilder() {
    return new com.online.shop.system.kafka.avro.model.ProductRatingAvroModel.Builder();
  }

  /**
   * Creates a new ProductRatingAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProductRatingAvroModel RecordBuilder
   */
  public static com.online.shop.system.kafka.avro.model.ProductRatingAvroModel.Builder newBuilder(com.online.shop.system.kafka.avro.model.ProductRatingAvroModel.Builder other) {
    if (other == null) {
      return new com.online.shop.system.kafka.avro.model.ProductRatingAvroModel.Builder();
    } else {
      return new com.online.shop.system.kafka.avro.model.ProductRatingAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new ProductRatingAvroModel RecordBuilder by copying an existing ProductRatingAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new ProductRatingAvroModel RecordBuilder
   */
  public static com.online.shop.system.kafka.avro.model.ProductRatingAvroModel.Builder newBuilder(com.online.shop.system.kafka.avro.model.ProductRatingAvroModel other) {
    if (other == null) {
      return new com.online.shop.system.kafka.avro.model.ProductRatingAvroModel.Builder();
    } else {
      return new com.online.shop.system.kafka.avro.model.ProductRatingAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProductRatingAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProductRatingAvroModel>
    implements org.apache.avro.data.RecordBuilder<ProductRatingAvroModel> {

    private java.util.UUID productID;
    private int rating;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.online.shop.system.kafka.avro.model.ProductRatingAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.productID)) {
        this.productID = data().deepCopy(fields()[0].schema(), other.productID);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.rating)) {
        this.rating = data().deepCopy(fields()[1].schema(), other.rating);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing ProductRatingAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.online.shop.system.kafka.avro.model.ProductRatingAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.productID)) {
        this.productID = data().deepCopy(fields()[0].schema(), other.productID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.rating)) {
        this.rating = data().deepCopy(fields()[1].schema(), other.rating);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'productID' field.
      * @return The value.
      */
    public java.util.UUID getProductID() {
      return productID;
    }


    /**
      * Sets the value of the 'productID' field.
      * @param value The value of 'productID'.
      * @return This builder.
      */
    public com.online.shop.system.kafka.avro.model.ProductRatingAvroModel.Builder setProductID(java.util.UUID value) {
      validate(fields()[0], value);
      this.productID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'productID' field has been set.
      * @return True if the 'productID' field has been set, false otherwise.
      */
    public boolean hasProductID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'productID' field.
      * @return This builder.
      */
    public com.online.shop.system.kafka.avro.model.ProductRatingAvroModel.Builder clearProductID() {
      productID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'rating' field.
      * @return The value.
      */
    public int getRating() {
      return rating;
    }


    /**
      * Sets the value of the 'rating' field.
      * @param value The value of 'rating'.
      * @return This builder.
      */
    public com.online.shop.system.kafka.avro.model.ProductRatingAvroModel.Builder setRating(int value) {
      validate(fields()[1], value);
      this.rating = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'rating' field has been set.
      * @return True if the 'rating' field has been set, false otherwise.
      */
    public boolean hasRating() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'rating' field.
      * @return This builder.
      */
    public com.online.shop.system.kafka.avro.model.ProductRatingAvroModel.Builder clearRating() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProductRatingAvroModel build() {
      try {
        ProductRatingAvroModel record = new ProductRatingAvroModel();
        record.productID = fieldSetFlags()[0] ? this.productID : (java.util.UUID) defaultValue(fields()[0]);
        record.rating = fieldSetFlags()[1] ? this.rating : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProductRatingAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProductRatingAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProductRatingAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<ProductRatingAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










