/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.online.shop.system.kafka.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ProductReviewContentUrlAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4535348212349961263L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProductReviewContentUrlAvroModel\",\"namespace\":\"com.online.shop.system.kafka.avro.model\",\"fields\":[{\"name\":\"productReviewID\",\"type\":\"int\"},{\"name\":\"productID\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"imageUrl\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"videoUrl\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ProductReviewContentUrlAvroModel> ENCODER =
      new BinaryMessageEncoder<ProductReviewContentUrlAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProductReviewContentUrlAvroModel> DECODER =
      new BinaryMessageDecoder<ProductReviewContentUrlAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProductReviewContentUrlAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProductReviewContentUrlAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProductReviewContentUrlAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ProductReviewContentUrlAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProductReviewContentUrlAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProductReviewContentUrlAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProductReviewContentUrlAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProductReviewContentUrlAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int productReviewID;
  private java.lang.String productID;
  private java.lang.String imageUrl;
  private java.lang.String videoUrl;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProductReviewContentUrlAvroModel() {}

  /**
   * All-args constructor.
   * @param productReviewID The new value for productReviewID
   * @param productID The new value for productID
   * @param imageUrl The new value for imageUrl
   * @param videoUrl The new value for videoUrl
   */
  public ProductReviewContentUrlAvroModel(java.lang.Integer productReviewID, java.lang.String productID, java.lang.String imageUrl, java.lang.String videoUrl) {
    this.productReviewID = productReviewID;
    this.productID = productID;
    this.imageUrl = imageUrl;
    this.videoUrl = videoUrl;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return productReviewID;
    case 1: return productID;
    case 2: return imageUrl;
    case 3: return videoUrl;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: productReviewID = (java.lang.Integer)value$; break;
    case 1: productID = value$ != null ? value$.toString() : null; break;
    case 2: imageUrl = value$ != null ? value$.toString() : null; break;
    case 3: videoUrl = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'productReviewID' field.
   * @return The value of the 'productReviewID' field.
   */
  public int getProductReviewID() {
    return productReviewID;
  }


  /**
   * Sets the value of the 'productReviewID' field.
   * @param value the value to set.
   */
  public void setProductReviewID(int value) {
    this.productReviewID = value;
  }

  /**
   * Gets the value of the 'productID' field.
   * @return The value of the 'productID' field.
   */
  public java.lang.String getProductID() {
    return productID;
  }


  /**
   * Sets the value of the 'productID' field.
   * @param value the value to set.
   */
  public void setProductID(java.lang.String value) {
    this.productID = value;
  }

  /**
   * Gets the value of the 'imageUrl' field.
   * @return The value of the 'imageUrl' field.
   */
  public java.lang.String getImageUrl() {
    return imageUrl;
  }


  /**
   * Sets the value of the 'imageUrl' field.
   * @param value the value to set.
   */
  public void setImageUrl(java.lang.String value) {
    this.imageUrl = value;
  }

  /**
   * Gets the value of the 'videoUrl' field.
   * @return The value of the 'videoUrl' field.
   */
  public java.lang.String getVideoUrl() {
    return videoUrl;
  }


  /**
   * Sets the value of the 'videoUrl' field.
   * @param value the value to set.
   */
  public void setVideoUrl(java.lang.String value) {
    this.videoUrl = value;
  }

  /**
   * Creates a new ProductReviewContentUrlAvroModel RecordBuilder.
   * @return A new ProductReviewContentUrlAvroModel RecordBuilder
   */
  public static com.online.shop.system.kafka.avro.model.ProductReviewContentUrlAvroModel.Builder newBuilder() {
    return new com.online.shop.system.kafka.avro.model.ProductReviewContentUrlAvroModel.Builder();
  }

  /**
   * Creates a new ProductReviewContentUrlAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProductReviewContentUrlAvroModel RecordBuilder
   */
  public static com.online.shop.system.kafka.avro.model.ProductReviewContentUrlAvroModel.Builder newBuilder(com.online.shop.system.kafka.avro.model.ProductReviewContentUrlAvroModel.Builder other) {
    if (other == null) {
      return new com.online.shop.system.kafka.avro.model.ProductReviewContentUrlAvroModel.Builder();
    } else {
      return new com.online.shop.system.kafka.avro.model.ProductReviewContentUrlAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new ProductReviewContentUrlAvroModel RecordBuilder by copying an existing ProductReviewContentUrlAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new ProductReviewContentUrlAvroModel RecordBuilder
   */
  public static com.online.shop.system.kafka.avro.model.ProductReviewContentUrlAvroModel.Builder newBuilder(com.online.shop.system.kafka.avro.model.ProductReviewContentUrlAvroModel other) {
    if (other == null) {
      return new com.online.shop.system.kafka.avro.model.ProductReviewContentUrlAvroModel.Builder();
    } else {
      return new com.online.shop.system.kafka.avro.model.ProductReviewContentUrlAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProductReviewContentUrlAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProductReviewContentUrlAvroModel>
    implements org.apache.avro.data.RecordBuilder<ProductReviewContentUrlAvroModel> {

    private int productReviewID;
    private java.lang.String productID;
    private java.lang.String imageUrl;
    private java.lang.String videoUrl;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.online.shop.system.kafka.avro.model.ProductReviewContentUrlAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.productReviewID)) {
        this.productReviewID = data().deepCopy(fields()[0].schema(), other.productReviewID);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.productID)) {
        this.productID = data().deepCopy(fields()[1].schema(), other.productID);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.imageUrl)) {
        this.imageUrl = data().deepCopy(fields()[2].schema(), other.imageUrl);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.videoUrl)) {
        this.videoUrl = data().deepCopy(fields()[3].schema(), other.videoUrl);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing ProductReviewContentUrlAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.online.shop.system.kafka.avro.model.ProductReviewContentUrlAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.productReviewID)) {
        this.productReviewID = data().deepCopy(fields()[0].schema(), other.productReviewID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.productID)) {
        this.productID = data().deepCopy(fields()[1].schema(), other.productID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.imageUrl)) {
        this.imageUrl = data().deepCopy(fields()[2].schema(), other.imageUrl);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.videoUrl)) {
        this.videoUrl = data().deepCopy(fields()[3].schema(), other.videoUrl);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'productReviewID' field.
      * @return The value.
      */
    public int getProductReviewID() {
      return productReviewID;
    }


    /**
      * Sets the value of the 'productReviewID' field.
      * @param value The value of 'productReviewID'.
      * @return This builder.
      */
    public com.online.shop.system.kafka.avro.model.ProductReviewContentUrlAvroModel.Builder setProductReviewID(int value) {
      validate(fields()[0], value);
      this.productReviewID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'productReviewID' field has been set.
      * @return True if the 'productReviewID' field has been set, false otherwise.
      */
    public boolean hasProductReviewID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'productReviewID' field.
      * @return This builder.
      */
    public com.online.shop.system.kafka.avro.model.ProductReviewContentUrlAvroModel.Builder clearProductReviewID() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'productID' field.
      * @return The value.
      */
    public java.lang.String getProductID() {
      return productID;
    }


    /**
      * Sets the value of the 'productID' field.
      * @param value The value of 'productID'.
      * @return This builder.
      */
    public com.online.shop.system.kafka.avro.model.ProductReviewContentUrlAvroModel.Builder setProductID(java.lang.String value) {
      validate(fields()[1], value);
      this.productID = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'productID' field has been set.
      * @return True if the 'productID' field has been set, false otherwise.
      */
    public boolean hasProductID() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'productID' field.
      * @return This builder.
      */
    public com.online.shop.system.kafka.avro.model.ProductReviewContentUrlAvroModel.Builder clearProductID() {
      productID = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'imageUrl' field.
      * @return The value.
      */
    public java.lang.String getImageUrl() {
      return imageUrl;
    }


    /**
      * Sets the value of the 'imageUrl' field.
      * @param value The value of 'imageUrl'.
      * @return This builder.
      */
    public com.online.shop.system.kafka.avro.model.ProductReviewContentUrlAvroModel.Builder setImageUrl(java.lang.String value) {
      validate(fields()[2], value);
      this.imageUrl = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'imageUrl' field has been set.
      * @return True if the 'imageUrl' field has been set, false otherwise.
      */
    public boolean hasImageUrl() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'imageUrl' field.
      * @return This builder.
      */
    public com.online.shop.system.kafka.avro.model.ProductReviewContentUrlAvroModel.Builder clearImageUrl() {
      imageUrl = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'videoUrl' field.
      * @return The value.
      */
    public java.lang.String getVideoUrl() {
      return videoUrl;
    }


    /**
      * Sets the value of the 'videoUrl' field.
      * @param value The value of 'videoUrl'.
      * @return This builder.
      */
    public com.online.shop.system.kafka.avro.model.ProductReviewContentUrlAvroModel.Builder setVideoUrl(java.lang.String value) {
      validate(fields()[3], value);
      this.videoUrl = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'videoUrl' field has been set.
      * @return True if the 'videoUrl' field has been set, false otherwise.
      */
    public boolean hasVideoUrl() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'videoUrl' field.
      * @return This builder.
      */
    public com.online.shop.system.kafka.avro.model.ProductReviewContentUrlAvroModel.Builder clearVideoUrl() {
      videoUrl = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProductReviewContentUrlAvroModel build() {
      try {
        ProductReviewContentUrlAvroModel record = new ProductReviewContentUrlAvroModel();
        record.productReviewID = fieldSetFlags()[0] ? this.productReviewID : (java.lang.Integer) defaultValue(fields()[0]);
        record.productID = fieldSetFlags()[1] ? this.productID : (java.lang.String) defaultValue(fields()[1]);
        record.imageUrl = fieldSetFlags()[2] ? this.imageUrl : (java.lang.String) defaultValue(fields()[2]);
        record.videoUrl = fieldSetFlags()[3] ? this.videoUrl : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProductReviewContentUrlAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProductReviewContentUrlAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProductReviewContentUrlAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<ProductReviewContentUrlAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










