/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.online.shop.system.kafka.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ShippingRequestAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6439213992415877110L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ShippingRequestAvroModel\",\"namespace\":\"com.online.shop.system.kafka.avro.model\",\"fields\":[{\"name\":\"orderID\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"orderAddress\",\"type\":{\"type\":\"record\",\"name\":\"OrderAddress\",\"fields\":[{\"name\":\"street\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"postalCode\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"city\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ShippingRequestAvroModel> ENCODER =
      new BinaryMessageEncoder<ShippingRequestAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ShippingRequestAvroModel> DECODER =
      new BinaryMessageDecoder<ShippingRequestAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ShippingRequestAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ShippingRequestAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ShippingRequestAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ShippingRequestAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ShippingRequestAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ShippingRequestAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ShippingRequestAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ShippingRequestAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String orderID;
  private com.online.shop.system.kafka.avro.model.OrderAddress orderAddress;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ShippingRequestAvroModel() {}

  /**
   * All-args constructor.
   * @param orderID The new value for orderID
   * @param orderAddress The new value for orderAddress
   */
  public ShippingRequestAvroModel(java.lang.String orderID, com.online.shop.system.kafka.avro.model.OrderAddress orderAddress) {
    this.orderID = orderID;
    this.orderAddress = orderAddress;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderID;
    case 1: return orderAddress;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderID = value$ != null ? value$.toString() : null; break;
    case 1: orderAddress = (com.online.shop.system.kafka.avro.model.OrderAddress)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'orderID' field.
   * @return The value of the 'orderID' field.
   */
  public java.lang.String getOrderID() {
    return orderID;
  }


  /**
   * Sets the value of the 'orderID' field.
   * @param value the value to set.
   */
  public void setOrderID(java.lang.String value) {
    this.orderID = value;
  }

  /**
   * Gets the value of the 'orderAddress' field.
   * @return The value of the 'orderAddress' field.
   */
  public com.online.shop.system.kafka.avro.model.OrderAddress getOrderAddress() {
    return orderAddress;
  }


  /**
   * Sets the value of the 'orderAddress' field.
   * @param value the value to set.
   */
  public void setOrderAddress(com.online.shop.system.kafka.avro.model.OrderAddress value) {
    this.orderAddress = value;
  }

  /**
   * Creates a new ShippingRequestAvroModel RecordBuilder.
   * @return A new ShippingRequestAvroModel RecordBuilder
   */
  public static com.online.shop.system.kafka.avro.model.ShippingRequestAvroModel.Builder newBuilder() {
    return new com.online.shop.system.kafka.avro.model.ShippingRequestAvroModel.Builder();
  }

  /**
   * Creates a new ShippingRequestAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ShippingRequestAvroModel RecordBuilder
   */
  public static com.online.shop.system.kafka.avro.model.ShippingRequestAvroModel.Builder newBuilder(com.online.shop.system.kafka.avro.model.ShippingRequestAvroModel.Builder other) {
    if (other == null) {
      return new com.online.shop.system.kafka.avro.model.ShippingRequestAvroModel.Builder();
    } else {
      return new com.online.shop.system.kafka.avro.model.ShippingRequestAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new ShippingRequestAvroModel RecordBuilder by copying an existing ShippingRequestAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new ShippingRequestAvroModel RecordBuilder
   */
  public static com.online.shop.system.kafka.avro.model.ShippingRequestAvroModel.Builder newBuilder(com.online.shop.system.kafka.avro.model.ShippingRequestAvroModel other) {
    if (other == null) {
      return new com.online.shop.system.kafka.avro.model.ShippingRequestAvroModel.Builder();
    } else {
      return new com.online.shop.system.kafka.avro.model.ShippingRequestAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for ShippingRequestAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ShippingRequestAvroModel>
    implements org.apache.avro.data.RecordBuilder<ShippingRequestAvroModel> {

    private java.lang.String orderID;
    private com.online.shop.system.kafka.avro.model.OrderAddress orderAddress;
    private com.online.shop.system.kafka.avro.model.OrderAddress.Builder orderAddressBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.online.shop.system.kafka.avro.model.ShippingRequestAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderID)) {
        this.orderID = data().deepCopy(fields()[0].schema(), other.orderID);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.orderAddress)) {
        this.orderAddress = data().deepCopy(fields()[1].schema(), other.orderAddress);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasOrderAddressBuilder()) {
        this.orderAddressBuilder = com.online.shop.system.kafka.avro.model.OrderAddress.newBuilder(other.getOrderAddressBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing ShippingRequestAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.online.shop.system.kafka.avro.model.ShippingRequestAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.orderID)) {
        this.orderID = data().deepCopy(fields()[0].schema(), other.orderID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.orderAddress)) {
        this.orderAddress = data().deepCopy(fields()[1].schema(), other.orderAddress);
        fieldSetFlags()[1] = true;
      }
      this.orderAddressBuilder = null;
    }

    /**
      * Gets the value of the 'orderID' field.
      * @return The value.
      */
    public java.lang.String getOrderID() {
      return orderID;
    }


    /**
      * Sets the value of the 'orderID' field.
      * @param value The value of 'orderID'.
      * @return This builder.
      */
    public com.online.shop.system.kafka.avro.model.ShippingRequestAvroModel.Builder setOrderID(java.lang.String value) {
      validate(fields()[0], value);
      this.orderID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderID' field has been set.
      * @return True if the 'orderID' field has been set, false otherwise.
      */
    public boolean hasOrderID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderID' field.
      * @return This builder.
      */
    public com.online.shop.system.kafka.avro.model.ShippingRequestAvroModel.Builder clearOrderID() {
      orderID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderAddress' field.
      * @return The value.
      */
    public com.online.shop.system.kafka.avro.model.OrderAddress getOrderAddress() {
      return orderAddress;
    }


    /**
      * Sets the value of the 'orderAddress' field.
      * @param value The value of 'orderAddress'.
      * @return This builder.
      */
    public com.online.shop.system.kafka.avro.model.ShippingRequestAvroModel.Builder setOrderAddress(com.online.shop.system.kafka.avro.model.OrderAddress value) {
      validate(fields()[1], value);
      this.orderAddressBuilder = null;
      this.orderAddress = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'orderAddress' field has been set.
      * @return True if the 'orderAddress' field has been set, false otherwise.
      */
    public boolean hasOrderAddress() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'orderAddress' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.online.shop.system.kafka.avro.model.OrderAddress.Builder getOrderAddressBuilder() {
      if (orderAddressBuilder == null) {
        if (hasOrderAddress()) {
          setOrderAddressBuilder(com.online.shop.system.kafka.avro.model.OrderAddress.newBuilder(orderAddress));
        } else {
          setOrderAddressBuilder(com.online.shop.system.kafka.avro.model.OrderAddress.newBuilder());
        }
      }
      return orderAddressBuilder;
    }

    /**
     * Sets the Builder instance for the 'orderAddress' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.online.shop.system.kafka.avro.model.ShippingRequestAvroModel.Builder setOrderAddressBuilder(com.online.shop.system.kafka.avro.model.OrderAddress.Builder value) {
      clearOrderAddress();
      orderAddressBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'orderAddress' field has an active Builder instance
     * @return True if the 'orderAddress' field has an active Builder instance
     */
    public boolean hasOrderAddressBuilder() {
      return orderAddressBuilder != null;
    }

    /**
      * Clears the value of the 'orderAddress' field.
      * @return This builder.
      */
    public com.online.shop.system.kafka.avro.model.ShippingRequestAvroModel.Builder clearOrderAddress() {
      orderAddress = null;
      orderAddressBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ShippingRequestAvroModel build() {
      try {
        ShippingRequestAvroModel record = new ShippingRequestAvroModel();
        record.orderID = fieldSetFlags()[0] ? this.orderID : (java.lang.String) defaultValue(fields()[0]);
        if (orderAddressBuilder != null) {
          try {
            record.orderAddress = this.orderAddressBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("orderAddress"));
            throw e;
          }
        } else {
          record.orderAddress = fieldSetFlags()[1] ? this.orderAddress : (com.online.shop.system.kafka.avro.model.OrderAddress) defaultValue(fields()[1]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ShippingRequestAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<ShippingRequestAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ShippingRequestAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<ShippingRequestAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










