server:
  port: 8186

logging:
  level:
    com.online.shop.system: DEBUG

spring:
  application:
    name: security-service
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/online_shop_system?currentSchema=security&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    platform: postgres
    #schema: classpath:schema.sql
    initialization-mode: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka